namespace minesweeper_cs
{
    internal static class Minesweeper
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            // auto-generated by VS
            ApplicationConfiguration.Initialize();
            Application.Run(new GameWindow());

            const int BeginnerBoardWidth = 9;
            const int BeginnerBoardHeight = 9;
            const int BeginnerMines = 10;

            Tile[,] board = new Tile[BeginnerBoardWidth, BeginnerBoardHeight];
            int mines = BeginnerMines;

        }
    }
}