namespace minesweeper_cs
{
    internal static class Minesweeper
    {
        [STAThread]
        static void Main()
        {
            // auto-generated by VS
            ApplicationConfiguration.Initialize();
            Application.Run(new GameWindow());

            // Constants for default game settings
            const int BeginnerBoardWidth = 9;
            const int BeginnerBoardHeight = 9;
            const int BeginnerMines = 10;

            Tile[,] board = new Tile[BeginnerBoardWidth, BeginnerBoardHeight];
            int mineCount = BeginnerMines;

        }
    }
}